name: Deploy

# on:
#   push:
#     tags:
#     - '*'
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    # - name: install Serverless plugins
    #   uses: serverless/github-action@master
    #   with:
    #     args: plugin install --name serverless-python-requirements

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --target . -r requirements.txt

    - name: Serverless deploy
      uses: serverless/github-action@master
      with:
        args: deploy --stage=prod --verbose
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # SLS_DEBUG: 1

    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: github
        SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
        SLACK_ICON: https://github.githubassets.com/favicon.ico
        SLACK_MESSAGE: 'ACME GW Deployment ${{ job.status }}'
        SLACK_TITLE: ACME GW
        SLACK_USERNAME: github-action
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}